CREATE TABLE FERRAMENTA
(
 ID INT PRIMARY KEY IDENTITY,
 NOME VARCHAR(50) NOT NULL,
 DISTRIBUICAO CHAR(1) NOT NULL,
 DTCADASTRO DATE NOT NULL,
 SITEOFICIAL VARCHAR(200) NOT NULL,
 IDCATEGORIA INT NOT NULL,
 IDFABRICANTE INT NOT NULL,
);
CREATE TABLE CATEGORIA
(
 ID INT PRIMARY KEY IDENTITY,
 DESCRICAO VARCHAR(50) NOT NULL,
);
CREATE TABLE FABRICANTE
(
 ID INT PRIMARY KEY IDENTITY,
 NOMEFANTASIA VARCHAR(50) NOT NULL,
);
ALTER TABLE FERRAMENTA ADD FOREIGN KEY(IDCATEGORIA) REFERENCES CATEGORIA (ID)
ALTER TABLE FERRAMENTA ADD FOREIGN KEY(IDFABRICANTE) REFERENCES FABRICANTE (ID)